### ISSUE TITLE
Can't work in firefox

### ISSUE THREAD

**Issue by GorodDetstva** [ppz-pro/file-bridge#7]

**Comment by daGaiGuanYu** [comment]
感谢反馈，等有时间了改

**Comment by daGaiGuanYu** [comment]
我刚看了一下，Firefox 不支持读取本地文件（缺少 [showDirectoryPicker](https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker#browser_compatibility) API），那么就没办法获取目录信息。

所以，Firefox 是没法做“文件提供端”的，但作为下载端是正常的。

除非将来 Firefox 实现了 showDirectoryPicker 或类似的 api，否则这个问题没办法解决。
